### ISSUE TITLE
你好，感谢你提供的这个项目，我觉得很棒，现在遇到一个问题

### ISSUE THREAD

**Issue by dotcool** [zmh-program/fystart#2]
就是我把你的这个页面直接接入我弄的一个论坛，论坛是wordpress搭建的，我把你的这个项目页面设置成首页的一部分。第一次刷新还好，但是我从首页点击其他链接进入下级页面的时候，还是显示这个项目的页面，我这边只是想把他放到首页的一部分。
请问这个如何实现呢？
我的网站是 [幸福无忧](https://www.51xfwy.com/)
第一个页面是正确的
![image](https://github.com/zmh-program/fystart/assets/6111056/91393b0d-d080-4a8c-96a0-93f049214c4d)
也可以正常的搜索和跳转，但是当我点击其他页面的时候他会跳转到这个项目的页面
![image](https://github.com/zmh-program/fystart/assets/6111056/f693463d-09b2-4164-a2ef-4cb0afb15618)
但这不是我想要的，我只需要他能在首页搜索就行

**Comment by Sh1n3zZ** [comment]
目前我访问并没有出现你所说的问题，尝试清除浏览器的本地缓存试试？
![VG{0T4DCSRJ%(V LUMX4TDS](https://github.com/zmh-program/fystart/assets/110708622/7d04bab0-807f-4969-bb16-79ffb6415fcb)

**Comment by zmh-program** [comment]
首先感谢您对我们fystart的支持！但是我仿佛无法复现这个问题
![图片](https://github.com/zmh-program/fystart/assets/112773885/2355d68e-1490-47f7-824c-6de1001219ba)
并没有出现您所说的问题，或许是因为Service Worker缓存技术的缘故，请您删除浏览器缓存后尝试是否可以访问

**Comment by dotcool** [comment]
确实是service work的问题，我停用了pwa，然后删除了浏览器的service worker现在可以了，感谢
