### ISSUE TITLE
1360x768 微调排版

### ISSUE THREAD

**Issue by luanyaolingwu** [zmh-program/fystart#4]
请求对 1360x768 的旧设备稍微调整版式，让它看起来不那么挤 [时钟位置稍微左移，然后把搜索框往上提一点点？]
![image](https://github.com/zmh-program/fystart/assets/105547626/7ae298a5-03df-458e-afcb-c6887f632541)
( 我感觉是挤了点；当然，不排除是我审美有问题…… )

**Comment by zmh-program** [comment]
OK 感谢反馈❤
